# Generated by Django 6.0.4 on 2026-06-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('culturas', '0001_initial'),
        ('fazendas', '0002_rename_aretotal_fazenda_area_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField()),
                ('severidade_max', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=50)),
                ('culturas_afetadas', models.CharField(help_text='Culturas separadas por vírgula', max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Praga',
                'verbose_name_plural': 'Tipos de Pragas',
                'db_table': 'tipos_pragas',
            },
        ),
        migrations.CreateModel(
            name='DadosClimaticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('fonte', models.CharField(choices=[('openweather', 'OpenWeather API'), ('ibge', 'IBGE'), ('inmet', 'INMET'), ('manual', 'Entrada Manual')], max_length=20)),
                ('temperatura_min', models.FloatField(help_text='Temperatura mínima em °C')),
                ('temperatura_max', models.FloatField(help_text='Temperatura máxima em °C')),
                ('umidade', models.FloatField(help_text='Umidade do ar em %')),
                ('precipitacao', models.FloatField(default=0, help_text='Precipitação em mm')),
                ('velocidade_vento', models.FloatField(default=0, help_text='Velocidade do vento em km/h')),
                ('condicao', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_climaticos', to='fazendas.fazenda')),
            ],
            options={
                'verbose_name': 'Dado Climático',
                'verbose_name_plural': 'Dados Climáticos',
                'db_table': 'dados_climaticos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='DeteccaoPraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('area_afetada_percentual', models.FloatField(help_text='Percentual da área afetada')),
                ('descricao', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('data_deteccao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('recomendacoes', models.TextField(blank=True, null=True)),
                ('tratamento_realizado', models.BooleanField(default=False)),
                ('data_tratamento', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes_praga', to='fazendas.fazenda')),
                ('plantio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deteccoes_praga', to='culturas.plantio')),
                ('tipo_praga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alertas.tipopraga')),
            ],
            options={
                'verbose_name': 'Detecção de Praga',
                'verbose_name_plural': 'Detecções de Pragas',
                'db_table': 'deteccoes_pragas',
                'ordering': ['-data_deteccao'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_alertas', models.IntegerField(default=0)),
                ('alertas_criticos', models.IntegerField(default=0)),
                ('alertas_altos', models.IntegerField(default=0)),
                ('alertas_medios', models.IntegerField(default=0)),
                ('alertas_baixos', models.IntegerField(default=0)),
                ('alertas_nao_lidos', models.IntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fazenda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='fazendas.fazenda')),
                ('ultimo_dado_climatico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alertas.dadosclimaticos')),
                ('ultima_praga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='alertas.deteccaopraga')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRAGA', 'Praga'), ('CLIMA_ADVERSO', 'Clima Adverso'), ('PLANTIO_FORA_EPOCA', 'Plantio Fora de Época'), ('ESTOQUE_BAIXO', 'Estoque Baixo'), ('MANUTENCAO_NECESSARIA', 'Manutenção Necessária'), ('OUTRO', 'Outro')], max_length=30)),
                ('severidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=20)),
                ('status', models.CharField(choices=[('NOVO', 'Novo'), ('EM_ANALISE', 'Em Análise'), ('ACIONADO', 'Acionado'), ('RESOLVIDO', 'Resolvido'), ('DESCARTADO', 'Descartado')], default='NOVO', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('recomendacoes', models.TextField(blank=True, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('data_notificacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='fazendas.fazenda')),
                ('plantio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='culturas.plantio')),
                ('usuarios_notificados', models.ManyToManyField(blank=True, related_name='alertas_recebidos', to=settings.AUTH_USER_MODEL)),
                ('dados_climaticos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertas.dadosclimaticos')),
                ('deteccao_praga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alertas.deteccaopraga')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'fazenda'], name='alertas_status_3ec77d_idx'), models.Index(fields=['severidade', 'criado_em'], name='alertas_severid_b50fc8_idx')],
            },
        ),
    ]
