# Generated by Django 6.0.4 on 2026-05-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(blank=True, max_length=255, null=True)),
                ('areTotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipoSolo', models.CharField(blank=True, choices=[('argissolos', 'Argissolos'), ('cambissolos', 'Cambissolos'), ('chermosolos', 'Chermosolos'), ('espodossolos', 'Espodossolos'), ('gleissolos', 'Gleissolos'), ('latossolos', 'Latossolos'), ('luvissolos', 'Luvissolos'), ('neossolos', 'Neossolos'), ('nitossolos', 'Nitossolos'), ('organossolos', 'Organossolos'), ('planossolos', 'Planossolos'), ('plintossolos', 'Plintossolos'), ('vertissolos', 'Vertissolos')], max_length=20, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('atualizadoEm', models.DateTimeField(auto_now=True)),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fazendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fazenda',
                'verbose_name_plural': 'Fazendas',
                'db_table': 'fazendas',
            },
        ),
    ]
