# Generated by Django 6.0.4 on 2026-05-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazendas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fazenda',
            old_name='areTotal',
            new_name='area_total',
        ),
        migrations.RenameField(
            model_name='fazenda',
            old_name='atualizadoEm',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='fazenda',
            old_name='criadoEm',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='fazenda',
            old_name='tipoSolo',
            new_name='tipo_solo',
        ),
        migrations.AlterField(
            model_name='fazenda',
            name='estado',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
