# Generated by Django 6.0.4 on 2026-06-21 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendas', '0002_rename_aretotal_fazenda_area_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('serialNumber', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('possui_telemetria', models.BooleanField(default=False)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazendas.fazenda')),
            ],
        ),
        migrations.CreateModel(
            name='Manutenção',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva')], default='PREVENTIVA', max_length=20)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EM_ANDAMENTO', 'Em andamento'), ('REALIZADA', 'Realizada')], default='PROGRAMADA', max_length=20)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('maquinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='maquinario.maquinario')),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('origem', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('maquinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='maquinario.maquinario')),
            ],
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=20)),
                ('motor_ligado', models.BooleanField(default=False)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('maquinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetrias', to='maquinario.maquinario')),
            ],
        ),
    ]
