# Generated by Django 6.0.4 on 2026-06-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendas', '0002_rename_aretotal_fazenda_area_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('COMPRA', 'Compra'), ('SERVICO', 'Serviço'), ('OUTRA', 'Outra')], default='OUTRA', max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('REJEITADA', 'Rejeitada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('custo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('requer_aprovacao', models.BooleanField(default=True, help_text='Se custo > R$ 5.000, requer aprovação')),
                ('motivo_rejeicao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='fazendas.fazenda')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'db_table': 'solicitacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
