# Generated by Django 6.0.4 on 2026-05-26 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fazendas', '0002_rename_aretotal_fazenda_area_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('mes_inicio', models.IntegerField()),
                ('mes_fim', models.IntegerField()),
            ],
            options={
                'db_table': 'culturas',
            },
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLANEJADO', 'Planejado'), ('EM_ANDAMENTO', 'Em Andamento'), ('PLANTADO', 'Plantado'), ('COLHIDO', 'Colhido'), ('PERDIDO', 'Perdido')], default='PLANEJADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='culturas.cultura')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fazendas.fazenda')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantios',
            },
        ),
        migrations.CreateModel(
            name='Laudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SOLO', 'Solo'), ('PRAGA', 'Praga'), ('RISCO', 'Risco'), ('GERAL', 'Geral')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('recomendacoes', models.TextField(blank=True, null=True)),
                ('ph_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('umidade_solo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_praga', models.CharField(blank=True, max_length=100, null=True)),
                ('severidade_praga', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_risco', models.CharField(blank=True, max_length=500, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agronomo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos', to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='laudos', to='fazendas.fazenda')),
                ('plantio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laudos', to='culturas.plantio')),
            ],
            options={
                'db_table': 'laudos',
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField()),
                ('area_colhida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colheitas', to=settings.AUTH_USER_MODEL)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colheitas', to='culturas.plantio')),
            ],
            options={
                'db_table': 'colheitas',
            },
        ),
    ]
