# Generated by Django 6.0.4 on 2026-06-21 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fazendas', '0002_rename_aretotal_fazenda_area_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('POR_USUARIO', 'Por Usuário'), ('POR_FAZENDA', 'Por Fazenda'), ('POR_ACAO', 'Por Ação'), ('POR_PERIODO', 'Por Período'), ('COMPLETO', 'Completo')], max_length=20)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('GERANDO', 'Gerando'), ('PRONTO', 'Pronto'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='auditoria/relatorios/')),
                ('formato', models.CharField(choices=[('CSV', 'CSV'), ('PDF', 'PDF'), ('XLSX', 'Excel'), ('JSON', 'JSON')], default='CSV', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('fazenda_filtro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazendas.fazenda')),
                ('usuario_filtro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios_sobre_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório de Auditoria',
                'verbose_name_plural': 'Relatórios de Auditoria',
                'db_table': 'relatorios_auditoria',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('CRIADO', 'Criado'), ('ATUALIZADO', 'Atualizado'), ('DELETADO', 'Deletado'), ('ACESSADO', 'Acessado'), ('EXPORTADO', 'Exportado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CANCELADO', 'Cancelado'), ('RESOLVIDO', 'Resolvido'), ('OUTRO', 'Outro')], max_length=20)),
                ('modulo', models.CharField(choices=[('ACCOUNTS', 'Contas'), ('FAZENDAS', 'Fazendas'), ('CULTURAS', 'Culturas'), ('ESTOQUE', 'Estoque'), ('MAQUINARIO', 'Maquinário'), ('ALERTAS', 'Alertas'), ('SOLICITACOES', 'Solicitações'), ('ADMIN', 'Administração'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nome_objeto', models.CharField(blank=True, help_text='Nome do objeto afetado', max_length=255)),
                ('dados_anteriores', models.JSONField(blank=True, help_text='JSON com valores anteriores', null=True)),
                ('dados_novos', models.JSONField(blank=True, help_text='JSON com valores novos', null=True)),
                ('campos_alterados', models.JSONField(blank=True, help_text='Lista de campos alterados', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('endpoint', models.CharField(blank=True, max_length=500)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('fazenda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='fazendas.fazenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'logs',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['usuario', 'criado_em'], name='logs_usuario_c7b7ee_idx'), models.Index(fields=['fazenda', 'criado_em'], name='logs_fazenda_9b75a9_idx'), models.Index(fields=['acao', 'modulo'], name='logs_acao_cf3fd7_idx')],
            },
        ),
    ]
